services:
  # db:
  #   image: postgres
  #   user: postgres
  #   volumes:
  #     - "pgdata:/var/lib/postgresql/data"
  #   environment:
  #     POSTGRES_PASSWORD: "postgresql"
  #   ports:
  #     - 5432:5432
  web:
    container_name: ${APACHE_DOCKER_IMG}
    environment:
      - ENV
    build: .
    volumes:
      - "/home/fsousa/src/passaprimeira:/var/www/public_html"
    ports:
      - ${WEB_SERVER_PORT}:80

# volumes:
#   pgdata:
